#!/bin/bash

# Read config file
. config/config.sh
# Get values
. data/configparser.sh

echo -e "\nUmVirt LFSAutoBuilder configuration"
echo -e "-----------------------------------\n"

echo "Target architecture: $LFS_TARGET_ARCH"
echo "Target init system: $LFS_TARGET_INIT"
echo